apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
# do not touch timers
#  timers:
#    holdTimeSeconds: 9
#    keepAliveTimeSeconds: 3
#
# no authent
#  authSecretRef: bgp-auth-secret
#
#  no multihop
#  ebgpMultihop: 4
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"

