apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "cilium-lb-ip-pool-arp"
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - start: 192.168.42.230
      stop: 192.168.42.239
  serviceSelector:
    matchLabels:
      announcement: arp
