apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: "2024-10-24T16:43:49Z"
  generation: 8
  labels:
    app: rello
  name: rello
  namespace: rello
  resourceVersion: "617608"
  uid: 9fb70800-f202-4d83-b116-a4a3bf35ee2b
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rello
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rello
    spec:
      containers:
      - env:
        - name: RELLO_REDIS_HOST
          value: redis
        - name: RELLO_REDIS_PORT
          value: "6379"
        - name: RELLO_REDIS_DB
          value: "0"
        image: shtouff/rello:0.2
        imagePullPolicy: Always
        name: rello
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2024-10-24T16:43:49Z"
    lastUpdateTime: "2024-10-25T10:43:02Z"
    message: ReplicaSet "rello-78b4dfd8cf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-10-25T23:05:07Z"
    lastUpdateTime: "2024-10-25T23:05:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
